### PR TITLE
Adding phenotype utilities

### PR DESCRIPTION
**Pull request by ekosmin**
Given two organisms, can now calculate the number of genotype changes to have their phenotypes match

### CODE REVIEW

**Comment by sfentress** [comment]
It would be good to get tests on this, since most of the library is otherwise covered, and these functions are apparently to be used by a third party (NCSU) so we'd want to be careful about losing their functionality in a later release.

**Comment by ekosmin** [comment]
Good point @sfentress, thanks for taking a look. Obviously it would be best if I could just copy unit tests from Geniblocks, where I took this code from, but there don't seem to be any. It looks like the Geniblocks code was taken from the older, Sproutcore code:

https://github.com/concord-consortium/Geniverse-SproutCore/blob/master/frameworks/geniverse/controllers/match.js

I tried looking for unit tests there but couldn't find anything, could I be missing something?

**Comment by sfentress** [comment]
If there isn't time to add tests for this and the breeding function in the later PR, you could just add a GitHub issue to the project so we can remember it.

**Comment by ekosmin** [comment]
Added an issue! Yesterday was my last day on the project, so I think the issue is the best I can do for now.

**Pull request merged**
